---
title: "Toolchain of a GADA Scientist"
abstract: digital EDC of a GADA scientist
date: last-modified
date-format: full
author: im@johnho.ca
license: "CC BY-NC-SA"
categories:
    - guide
format:
    html:
        mermaid:
            theme: forest
            securityLevel: loose
        toc: true
        toc-depth: 4
        toc-expand: 3
        toc-title: Contents
        toc-location: left
        link-external-icon: true
        link-external-newwindow: true
draft: false
execute:
  echo: false
---

# hardware
MBP 2023 with M2 Max & 32GB RAM

# The Toolchain

* docker: `brew install --cask docker`
    * you will need to follow [this guide here](https://stackoverflow.com/a/43365425)
    * and you do want the cask version because the [official version for Mac is a GUI](https://stackoverflow.com/a/40523608)... i.e. there are no headless version
    * my [docker cheatsheet](https://gist.github.com/ohjho/af86af1c1dfab4979f6d0543000351cd)

* [macmon](https://medium.com/@vladkens/mac-usage-monitor-in-terminal-meet-macmon-3a3391995224):
    * TUI for monitoring resource use on Apple's ARM architecture MacBook
    * like a much better version of `htop`
    * install: `brew update && brew install macmon`

* [Sequel-Ace](https://github.com/Sequel-Ace/Sequel-Ace?tab=readme-ov-file):
    * MySQL management for macOS
    * install: `brew update && brew install --cask sequel-ace`

* [yt-dlp](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#installation)
    * feature-rich CLI audio/video downloader with support for [thousand of sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md),
    including YouTube and Soundcloud
    * it's a bit more advanced with the use of
    [format selection](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#format-selection)
    for selecting the right stream but it also uses `ffmpeg` under the hood to
    merge audio and video streams.
    Format selection [examples are available](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#format-selection-examples).
    * install: `pipx install "yt-dlp[default]"`

# python environments
use to managed using `pyenv` and the `virtualenvwrapper` but
for python based cli I use `pipx`. See [here](https://gist.github.com/ohjho/8e2556d786b132d724b3914728c7c82f)
for details on full setup.

As of 2025 however, I manage both python versions and virtual environments with [uv](using-uv.qmd)
